# Service name
spring.application.name=post-service

# DB Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/post_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update

# Port for this microservice
server.port=${SERVER_PORT:8083}


# Resilience4j - Circuit Breaker - Common config (used by all CBs)
resilience4j.circuitbreaker.configs.default.slidingWindowSize=1
resilience4j.circuitbreaker.configs.default.minimumNumberOfCalls=1
resilience4j.circuitbreaker.configs.default.failureRateThreshold=50
resilience4j.circuitbreaker.configs.default.waitDurationInOpenState=10s

# Instances
resilience4j.circuitbreaker.instances.userServiceCB.baseConfig=default
resilience4j.circuitbreaker.instances.likeServiceCB.baseConfig=default
resilience4j.circuitbreaker.instances.commentServiceCB.baseConfig=default

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
