# Service name
spring.application.name=follow-service

# DB Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/friend_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:root}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Port for this microservice
server.port=${SERVER_PORT:8082}

# Eureka Client Configuration
eureka.client.service-url.defaultZone=${EUREKA_SERVICE_URL:http://localhost:8761/eureka}
eureka.instance.prefer-ip-address=true
